MVC.PL/Controllers/EmployeeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVC.BLL.Interfaces;
using MVC.DAL.Models;
using MVC.PL.Helper;
using MVC.PL.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC.PL.Controllers
{
	[Authorize]

	public class EmployeeController : Controller
	{
		
		private readonly IUnitOfWork _unitOfWork;
		private readonly IMapper _mapper;

		

		public EmployeeController(IUnitOfWork unitOfWork, IMapper mapper)
		{
			_mapper = mapper;
			_unitOfWork = unitOfWork;
		}




		#region index
		public async Task<IActionResult> Index(string SearchInput)
		{
			var employees = Enumerable.Empty<Employee>();
			if (string.IsNullOrWhiteSpace(SearchInput))
			{
				employees = await _unitOfWork.employeeRepository.GetAll();
			}
			else
			{
				employees = await _unitOfWork.employeeRepository.GetByName(SearchInput);
			}
			var res = _mapper.Map<IEnumerable<EmployeeViewModel>>(employees);
			return View(res);
		}
		#endregion



		#region Create
		[HttpGet]

		public IActionResult Create()
		{
			return View();
		}



		[HttpPost]
		public async Task<IActionResult> Create(EmployeeViewModel model)
		{
			if (ModelState.IsValid)
			{
				model.ImageName = DocumentSettings.UploadFile(model.Image, "images");


				var employee = _mapper.Map<Employee>(model);

				_unitOfWork.employeeRepository.Add(employee);
				int count = await _unitOfWork.Complete();
				if (count > 0)

				{
					TempData["Message"] = "Employee Added";
				}
				else
				{
					TempData["Message"] = "Employee NOT Added";

				}
				return RedirectToAction(nameof(Index));
			}

			return View(model);
		}

        #endregion

        #region Details
        [HttpGet]
		public async Task<IActionResult> Details(int? id, string viewName = "Details")
		{
			if (id is null)
			{
				return BadRequest();
			}
			var employee = await _unitOfWork.employeeRepository.GetById(id.Value);

			if (employee is null)
				return NotFound();
			var employeeViewModel = _mapper.Map<EmployeeViewModel>(employee);

			return View(viewName, employeeViewModel);
		} 
		#endregion

		#region Edit
		[HttpGet]
		public async Task<IActionResult> Edit(int? id)
		{
			return await Details(id, "Edit");
		}



		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit([FromRoute] int? id, EmployeeViewModel model)
		{
			if (id != model.Id)
				return BadRequest();

			if (ModelState.IsValid)
			{
				if (model.ImageName is not null)
				{
					DocumentSettings.DeleteFile(model.ImageName, "images");

				}
				model.ImageName = DocumentSettings.UploadFile(model.Image, "images");
				var employee = _mapper.Map<Employee>(model);
				_unitOfWork.employeeRepository.Update(employee);
				int count = await _unitOfWork.Complete();
				if (count > 0)
				{
					return RedirectToAction(nameof(Index));
				}
			}

			return View();
		}

		#endregion

		#region Delete
		[HttpGet]
		public async Task<IActionResult> Delete(int? id)
		{
			return await Details(id, "Delete");

		}

		[HttpPost]
		[ValidateAntiForgeryToken]

		public async Task<IActionResult> Delete([FromRoute] int? id, EmployeeViewModel model)
		{
			if (id != model.Id)
				return BadRequest();


			var employee = _mapper.Map<Employee>(model);

			_unitOfWork.employeeRepository.Delete(employee);
			int count = await _unitOfWork.Complete();
			if (count > 0)
			{
				if (model.ImageName is not null)
				{
					DocumentSettings.DeleteFile(model.ImageName, "images");

				}
				return RedirectToAction(nameof(Index));
			}


			return View();
		}
	#endregion
	} 
}

MVC.PL/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC.DAL.Models;
using MVC.PL.Helper;
using MVC.PL.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC.PL.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public RoleController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        #region Index
        public async Task<IActionResult> Index(string SearchInput)
        {
            var Roles = Enumerable.Empty<RoleViewModel>();

            if (string.IsNullOrEmpty(SearchInput))
            {
                Roles = await _roleManager.Roles.Select(R => new RoleViewModel()
                {
                    Id = R.Id,
                    RoleName = R.Name
                }).ToListAsync();
            }
            else
            {
                Roles = await _roleManager.Roles.Where(E => E.Name.ToLower().Contains(SearchInput.ToLower()))
                                                                            .Select(R => new RoleViewModel()
                                                                            {
                                                                                Id = R.Id,
                                                                                RoleName = R.Name

                                                                            }).ToListAsync();
            }
            return View(Roles);
        }
        #endregion

        #region Create
        [HttpGet]

        public IActionResult Create()
        {
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role =new IdentityRole()
                { 
                    Name=model.RoleName
                };
              var result=  await _roleManager.CreateAsync(role);
                if (result.Succeeded)
                {
                     return RedirectToAction(nameof(Index));

                }
                ModelState.AddModelError(string.Empty, "Invalid!! ");
            }

            return View(model);
        }

        #endregion

        #region Details
        public async Task<IActionResult> Details(string? id, string viewName = "Details")
        {
            if (id is null)
            {
                return BadRequest();
            }
            var RoleFormDb = await _roleManager.FindByIdAsync(id);
            if (RoleFormDb is null)
                return BadRequest();
            var role = new RoleViewModel()
            {
                Id = RoleFormDb.Id,
                RoleName = RoleFormDb.Name,
               
            };

            return View(viewName, role);
        }
        #endregion



        #region Edit
        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {
            return await Details(id, "Edit");
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string? id, RoleViewModel model)
        {
            if (id != model.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {

                var RoleFormDb = await _roleManager.FindByIdAsync(id);
                if (RoleFormDb is null)
                    return BadRequest();

                RoleFormDb.Name = model.RoleName;
               
                await _roleManager.UpdateAsync(RoleFormDb);

                return RedirectToAction(nameof(Index));

            }

            return View(model);
        }

        #endregion

        #region Delete
        [HttpGet]
        public async Task<IActionResult> Delete(string? id)
        {
            return await Details(id, "Delete");

        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Delete([FromRoute] string? id, RoleViewModel model)
        {
            if (id != model.Id)
                return BadRequest();


            if (ModelState.IsValid)
            {

                var RoleFormDb = await _roleManager.FindByIdAsync(id);
                if (RoleFormDb is null)
                    return BadRequest();

                RoleFormDb.Name = model.RoleName;

                await _roleManager.DeleteAsync(RoleFormDb);
                return RedirectToAction(nameof(Index));
            }



            return View();
        }
        #endregion



        #region Add Or Remove Users
        [HttpGet]
        public async Task<IActionResult> AddOrRemoveUsers(string roleId)
        {
            var role =await _roleManager.FindByIdAsync(roleId);


            if (role is null)
                return BadRequest();

            ViewData["id"]=roleId;
            var Users =await _userManager.Users.ToListAsync();

            var UsersInRole = new List<UserInRoleViewModel>();
            foreach (var user in Users)
            {
                var UserInRole = new UserInRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if(await _userManager.IsInRoleAsync(user, role.Name))
                {
                    UserInRole.IsSelected=true;

                }
                else
                {
                    UserInRole.IsSelected=false;
                }
                UsersInRole.Add(UserInRole);
            }
            return View(UsersInRole);
        }
        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUsers(string roleId,List<UserInRoleViewModel> users)
        {
            var role = await _roleManager.FindByIdAsync(roleId);


            if (role is null)
                return BadRequest();

            if(ModelState.IsValid)
            {
                foreach (var user in users)
                {
               
                    var AppUser =await _userManager.FindByIdAsync(user.UserId);
                    if (AppUser is not null)
                    {
                        if (user.IsSelected && ! await _userManager.IsInRoleAsync(AppUser, role.Name))
                        {

                            await _userManager.AddToRoleAsync(AppUser, role.Name);
                        }
                        else if(!user.IsSelected && await _userManager.IsInRoleAsync(AppUser, role.Name))
                        {
                            await _userManager.RemoveFromRoleAsync(AppUser, role.Name);
                        }
                    }
                    
                }
                   return RedirectToAction(nameof(Edit),new {id= roleId});

            }
           
            return View(users);
        }
        #endregion
    }
}

MVC.PL/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC.DAL.Models;
using MVC.PL.Helper;
using MVC.PL.ViewModels;
using System.Collections;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace MVC.PL.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class UserController : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly SignInManager<ApplicationUser> _signInManager;

		public UserController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
		{
			_userManager = userManager;
			_signInManager = signInManager;
		}
		#region Index
		public async Task<IActionResult> Index(string SearchInput)
		{
			var Users = Enumerable.Empty<UserViewModel>();

			if (string.IsNullOrEmpty(SearchInput))
			{
				Users = await _userManager.Users.Select(U => new UserViewModel()
				{
					Id = U.Id,
					FirstName = U.FirstName,
					LastName = U.LastName,
					Email = U.Email,
					Roles = _userManager.GetRolesAsync(U).Result
				}).ToListAsync();
			}
			else
			{
				Users = await _userManager.Users.Where(E => E.Email.ToLower().Contains(SearchInput.ToLower()))
																			.Select(U => new UserViewModel()
																			{
																				Id = U.Id,
																				FirstName = U.FirstName,
																				LastName = U.LastName,
																				Email = U.Email,
																				Roles = _userManager.GetRolesAsync(U).Result
																			}).ToListAsync();
			}
			return View(Users);
		}
        #endregion



        #region Details
        public async Task<IActionResult> Details(string? id, string viewName = "Details")
        {
            if (id is null)
            {
                return BadRequest();
            }
          var userFormDb = await _userManager.FindByIdAsync(id);
			if (userFormDb is null)
				return BadRequest();
			var user = new UserViewModel()
			{
				Id = userFormDb.Id,
				FirstName = userFormDb.FirstName,
				LastName = userFormDb.LastName,
				Email = userFormDb.Email,
				Roles = _userManager.GetRolesAsync(userFormDb).Result
			};

            return View(viewName, user);
        }
        #endregion



        #region Edit
        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {
            return await Details(id, "Edit");
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string? id, UserViewModel model)
        {
            if (id != model.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {

                var userFormDb = await _userManager.FindByIdAsync(id);
                if (userFormDb is null)
                    return BadRequest();

                userFormDb.FirstName = model.FirstName;
                userFormDb.LastName = model.LastName;
                userFormDb.Email = model.Email;
               await _userManager.UpdateAsync(userFormDb);

                return RedirectToAction(nameof(Index));
                
            }

            return View();
        }

        #endregion

        #region Delete
        [HttpGet]
        public async Task<IActionResult> Delete(string? id)
        {
            return await Details(id, "Delete");

        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Delete([FromRoute] string? id, UserViewModel model)
        {
            if (id != model.Id)
                return BadRequest();


            if (ModelState.IsValid)
            {

                var userFormDb = await _userManager.FindByIdAsync(id);
                if (userFormDb is null)
                    return BadRequest();

                await _userManager.DeleteAsync(userFormDb);
                return RedirectToAction(nameof(Index));
            } 
            


            return View();
        }
        #endregion
    }
}

MVC.PL/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title> @ViewData["Title"] </title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/AuthStyle.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Creative @ViewData["Title"] Form</h1>
		@RenderBody()
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>

	@await RenderSectionAsync("ValidationScriptSection", required: false)
</body>
</html>

MVC.PL/Views/Shared/_ButtonsPartialView.cshtml
@model string

<td>
    <a asp-action="Details" asp-route-id="@Model" class="btn btn-warning">
        <i class="fa-solid fa-eye"></i>Details
    </a>
</td>
<td>
    <a asp-action="Edit" asp-route-id="@Model" class="btn btn-success">
        <i class="fa-solid fa-eye"></i> Update
    </a>
</td>
<td>
    <a asp-action="Delete" asp-route-id="@Model" class="btn btn-danger">
        <i class="fa-solid fa-eye"></i>Delete
    </a>
</td>

MVC.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav justify-content-end flex-grow-1">
                      @*   @if (User.IsInRole("Admin"))
                        { *@
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                            </li>
                        @* } *@
                        <li class="nav-item">
                            <a class="nav-link text-light btn btn-danger" asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Demo.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("ValidationScriptSection", required: false)
</body>
</html>